### ISSUE TITLE
"Add line tags" button doesn't take comments into account

### ISSUE THREAD

**Issue by xsduan** [YarnSpinnerTool/YarnSpinner#291] opened 2021-01-17 23:52 UTC
I am not sure if this is on your radar yet so sorry if this has already been fixed.

When I use "add line tags" it doesn't take into account that there could be inline comments, so it doesn't register the inserted line tags.

```
title: test
tags:
---
Test: I am a test line! // i am comment
===
```

If you press the "add new line" button it just keeps on adding new lines to the end, like so:

```
title: test
tags:
---
Test: I am a test line! // i am comment #line:062ac89 #line:02798bb #line:0f56b6d #line:04df7eb #line:0a209ee #line:05530ac
===
```

obviously, this should be how it looks like:

```
title: test
tags:
---
Test: I am a test line! #line:062ac89 // i am comment
===
```

I am unsure about the spacing but I assume that gets trimmed anyways.

I can pretty easily get around that by not using inline comments in localizable lines but thought I'd let you know anyways as it was a bit unclear to figure out.

  - Yarn Spinner Version: v2.0.0-beta2
  - Unity Version: 2020.2.1f1

**Comment by desplesda** [comment] 2021-07-09 03:42
This appears to be a duplicate of #258.

**Closed by desplesda** 2021-07-09 03:42 UTC
Labels: bug, duplicate
