### ISSUE TITLE
Bump up antlr4 version?

### ISSUE THREAD

**Issue by thautwarm** [YarnSpinnerTool/YarnSpinner#306] opened 2021-10-25 03:27 UTC
Hard to say it's a bug so I didn't choose a issue template...
The background i,  I'm using both Antlr4.Runtime.Standard and YarnSpinner in one Unity project. 
However, it seems that YarnSpinner are using Antlr 4.7.1 while another usage of Antlr4 depends on Antlr 4.9.
I wonder if there is a particular reason for locking Antlr4 version? So far things do work but I'm afraid of prospective incompatibility.

**Comment by desplesda** [comment] 2021-12-15 05:57
Updating our version of Antlr to 4.9 would be a short-term fix, but doesn't fix the underlying problem of DLL collisions. As such, I'm considering this issue to actually be a duplicate of #307, and will therefore close it. We'll have a better fix for this category of issue soon.

**Closed by desplesda** 2021-12-15 05:57 UTC
Labels: bug
