### ISSUE TITLE
Attributes Are NOT Working! - Yarn Editor

### ISSUE THREAD

**Issue by SethDharma** [YarnSpinnerTool/YarnSpinner#274] opened 2020-09-16 14:56 UTC
There's seems to be an error every time I use an attribute like color, bold, italics, etc. It might be a compiler issue, seems like its not recognizing the syntax. 

For example, when using the text color, it throws this error when I import the Yarn file into Unity - **(Error on line 6 at position 9 / mismatched input / FORMAT_FUNCTION_EXPRESSION_START)**

**Comment by McJones** [comment] 2020-09-17 10:42
Could you please give us a bit more detail into what is the issue, such as the line of yarn that is causing the error.
Without more details unfortunately there isn't much to go on.

**Comment by SethDharma** [comment] 2020-09-17 12:49
Absolutely! For example, I try to use **(Bobby: [color=#ff0000]Hey, its been a long time![/color]).** This is the same with, bold, italics, etc. It throws and error when I import them into Unity.

The specific error for the color line is, **(Error on line 6 at position 15: token recognition error at '#')**

Hopefully this provides more info!

**Comment by McJones** [comment] 2020-09-18 01:38
ah ok I see what the problem is.
In Yarn Spinner the `#` symbol is a reserved symbol, you can't use it in your lines. What most people do when they need to use it is choose a new symbol such as `^` and then swap it back for the `#` after the line is returned to them by Yarn Spinner.

Does changing that fix the issue?

**Comment by SethDharma** [comment] 2020-09-20 12:40
Thank you so much, I did figure it out by using custom commands! But, there's seems to be one more bug I just cant fix. To start dialogue I have triggers, and if the player is in that trigger and presses (E) then it calls the start dialogue. BUT, for some reason there's 2 other keys that trigger it as well, (Lft Ctrl & Lft Mouse Button). Are there a default inputs for Yarn Spinner, I literally can't figure this one out.

**Comment by desplesda** [comment] 2021-07-09 03:41
@SethDharma This looks like a different issue to the one you initially filed in this thread; if you're still seeing this new issue in Yarn Spinner for Unity, can you please file a new issue about it there? (Thanks for filing this! Given that your original problem appears to be resolved, I'll go ahead and close this now.)

**Closed by desplesda** 2021-07-09 03:41 UTC
Labels: bug
