### ISSUE TITLE
In Memory Variable Storage fails to operate data in Linux in Unity

### ISSUE THREAD

**Issue by Thalslaw** [YarnSpinnerTool/YarnSpinner#235] opened 2020-04-28 13:03 UTC
Currently, when I put <<set $Torpedo_Familiar to 1>> to change the value of a preset number (0) describing whether or not the player is familiar with the torpedo relevant to my narrative, the variable does not change. I am using Unity 2019.3.6f1 and the most recent version of Yarn. I use this Unity version through the UnityHub, where my OS is the most recent version of Linux Mint.

**Comment by Thalslaw** [comment] 2020-04-30 11:20
Turns out that the issue relates to how the Unity Editor serializes its fields.

I produced this bug given that I was looking in the inspector window while playing the game in the editor. However, the game behaves correctly when the game is built.

I also have a tentative solution on how to make the In Memory Variable Storage container behave correctly for users of Linux Unity. 
The tentative solution produces variables that follow this pattern: 
// Fields
[SerializeField]
private bool _foo;
// Properties
public bool foo
{
	get
	{ 
		return _foo;
	}
	set
	{ 
		_foo = value;
	}
}
This produces behaviour where the inspector behaves properly when the editor is used to test game features.

**Comment by desplesda** [comment] 2020-05-06 05:23
Thank you for this bug report! I feel like I don't quite understand the problem (I get that there's a problem, I just don't understand what it _is_.)

Could you describe what you're doing, what you're expecting to see in response, and what you're actually seeing in response?

**Comment by Thalslaw** [comment] 2020-05-06 09:57
Hi Jon

What I am doing is running a fairly complex yarn script that attempted initially to follow the documentation and use the imvs as a state handler for a bunch of loops in my narrative. 

What I expected to be able to do is click the play button in the editor in order to test some states of the game. Those state changes in the inspector did not change any of the behaviour of the game. 

Example tweaks and investigations: 
<<set $thing to 1>>
this doesn't show up in the console. it doesn't change the behaviour of the fields in the inspector in unity in or out of playmode. The game 'builds' and executes the game correctly from raw start but does not allow for state investigations while devving.
<<Set $thing to 1>> 
This does show up in the console. It doesn't do anything or produce the expected behaviour when the game is built. 

The things that I do to get things serializing with expected behaviour is to separate fields and properties (use a _foo for each foo so that it references the same area of memory), render the fields private and then manually serialise them (requires some pretty tight public propertied accessor code).

That produces expected behaviour. But only in examples when I've got, like, a bunch of variables elsewhere in the game and not a dynamic list operated by yarn commands?

Kind regards

Connor


   On Wednesday, 6 May 2020, 06:23:31 BST, Jon Manning <notifications@github.com> wrote:  
 
 


Thank you for this bug report! I feel like I don't quite understand the problem (I get that there's a problem, I just don't understand what it is.)

Could you describe what you're doing, what you're expecting to see in response, and what you're actually seeing in response?

**Comment by janmaslov** [comment] 2020-05-09 09:32
It's still unclear. Is this an issue of C# Dictionaries not being serialized by default and you trying to work around that by hardcoding variable properties that you then set from Yarn scripts?

Out of the box the InMemoryVariableStorage holds the variables in a Dictionary, and it has an array of default variables (see the DefaultVariable class defined in the InMemoryVariableStorage class). These default variables are thrown into the Dictionary when the game starts. Changes to the variables won't be reflected in the default variables array, since the array is only used to populate the Dictionary at the beginning of the game. The Dictionary is what holds the live variables that change when you set variables in Yarn scripts.

To view the variables as you change them, the InMemoryVariableStorage provides you with the debugTextView variable. If you plug a Unity UI Text Component into there, it will output the contents of the Dictionary on screen. And changes to variables will be reflected in the output.

This is suboptimal for sure. The alternative is to serialize the Dictionary so that the Unity Editor understands it. There are ready-made implementations for that, which you'll have to explore, or write your own serializer (for example serialize the Dictionary into two Lists, which is crude, but works). The problem is that Yarn.Value (the Type of the values in the Dictionary) can't be easily serialized automatically, so you'll have to also make a serializer for that.

**Comment by Thalslaw** [comment] 2020-05-13 08:40
Hey man

That's a useful explanation. You recognised and understood my issue; I implemented a solution based on your response as a result. 

Thanks.

C


    On Saturday, 9 May 2020, 10:33:01 BST, janmaslov <notifications@github.com> wrote:  
 
 


It's still unclear. Is this an issue of C# Dictionaries not being serialized by default and you trying to work around that by hardcoding variable properties that you then set from Yarn scripts?

Out of the box the InMemoryVariableStorage holds the variables in a Dictionary, and it has an array of default variables (see the DefaultVariable class defined in the InMemoryVariableStorage class). These default variables are thrown into the Dictionary when the game starts. Changes to the variables won't be reflected in the default variables array, since the array is only used to populate the Dictionary at the beginning of the game. The Dictionary is what holds the live variables that change when you set variables in Yarn scripts.

To view the variables as you change them, the InMemoryVariableStorage provides you with the debugTextView variable. If you plug a Unity UI Text Component into there, it will output the contents of the Dictionary on screen. And changes to variables will be reflected in the output.

This is suboptimal for sure. The alternative is to serialize the Dictionary so that the Unity Editor understands it. There are ready-made implementations for that, which you'll have to explore, or write your own serializer (for example serialize the Dictionary into two Lists, which is crude, but works). The problem is that Yarn.Value (the Type of the values in the Dictionary) can't be easily serialized automatically, so you'll have to also make a serializer for that.

**Comment by desplesda** [comment] 2020-05-14 01:24
Excellent! I'll close this issue now; please add more to this thread if you need more help.

**Closed by desplesda** 2020-05-14 01:24 UTC
Labels: bug
