### ISSUE TITLE
Third Closing Square Brace on Dialogue option parse error

### ISSUE THREAD

**Issue by krystalCoconut** [YarnSpinnerTool/YarnSpinner#295] opened 2021-02-24 07:34 UTC
**What is the current behavior?**

Yarn file is not recognized properly in the unity editor. 

This was the yarn file. The error occurs on import/reimport. Reimporting all does not fix it either. 

```
title: KrystalTest
tags: 
colorID: 0
position: 609,188
---
Dear Krystal,||
<<wait 1>>
This is a simple test of the email system|
<<wait 0.5>>
If you have any questions let me know.
<<wait 0.5>>
I hope it works||
<<wait 1>>
Test
[[How does email on this work?|HowToEmail]]]
===
title: HowToEmail
tags: 
colorID: 0
position: 609,448
---
Test 2
===
```

**What is the expected behavior?**

Indicate a parse error

**Please tell us about your environment:**
  
  - Yarn Spinner Version: id assume 1.2.0, but i installed via the git package in unity package manager
  - Unity Version: 2020.2.3f1

**Other information** 

![image](https://user-images.githubusercontent.com/51192306/108963900-b99a7e00-76b5-11eb-896f-8d1bb7ffa29e.png)

**Comment by desplesda** [comment] 2021-07-09 03:45
This appears to be a duplicate of #257. Closing as such!

**Closed by desplesda** 2021-07-09 03:45 UTC
Labels: bug, duplicate
