### ISSUE TITLE
Problem Parsing Complex if-statements

### ISSUE THREAD

**Issue by Senshaij** [YarnSpinnerTool/YarnSpinner#71] opened 2017-04-20 11:57 UTC
I found Issue #53 , but it did not answer my question. I looked in the documentation, but did not see a solution there either for this type of if-statement.

My issue is that I have "complex" if-statements such as this:
<<if (($var1 > 5 and $var2 < 300) or ($var1 < 6 and $var2 >= 200 and $var2 < 300)) and ($var3 is false and $var4 >= 3 and $var5 < 100)>>[[next node|nextNode]]<<endif>>

and the parser seems to get suck on this line in this node when adding the statements to the _statements list and I'm not sure why. I've looked at the parsed text and it parses the whole node just fine from what I can see. This is the first "complex" if-statement I have in my story, and if I change it to an if-statement with no parenthesis, it moves past this node just fine.

I do need if-statements like this, but if there is some other way I should write them, please let me know.

**Comment by desplesda** [comment] 2017-04-21 01:56
Looking into it!

**Comment by Senshaij** [comment] 2017-04-26 11:08
Thank you for looking into this!

I do have one more question about "weird" if-statement conditions if anyone happens to know:
I would love to be able to use modular (%) as part of an if-statement. Ex: if $var % 3 is 0. However, it seems that modular is not supported.
I could get around this with division, but only if division returns a double/float and not an integer. Does $var / 3 when $var = 4 return an integer (1) or a double/float (1.3333)?

My "last resort" will be to write a function to perform mod for me, but I wanted to try using the built-in tools first.

Thanks!

**Comment by desplesda** [comment] 2017-04-26 11:17
I'm probably not going to add syntax or features that let you define arbitrary new operators, because Yarn's focus is dialogue and not all-purpose programming, but modulus is a common enough operator that I think it should be included in the core language. I'll add a new issue for it.

**Comment by desplesda** [comment] 2017-04-26 11:20
Added issue #73 to track this. Please continue any discussion about this in that issue, please! 👍

**Comment by TheMartianLife** [comment] 2019-07-14 04:28
Modulo operator added in #77. To diagnose your initial issue we'll just need to attempt to reproduce the error on our end. Working on it! We'll let you know how it goes :)

**Comment by McJones** [comment] 2020-02-29 18:05
There hasn’t been any activity on this in a while and I believe it is fixed in the 1.1 beta so I am closing this issue.
If the issue reappears please open a new issue.

**Closed by McJones** 2020-02-29 18:05 UTC
Labels: bug
