### ISSUE TITLE
Yarn commands not called unless the text is displayed

### ISSUE THREAD

**Issue by PascalLadalle** [YarnSpinnerTool/YarnSpinner#236] opened 2020-04-30 15:07 UTC
Not sure if it's really a bug, but I'm able to check for **tags** without displaying the text of a node, but I'm unable to check for **commands** without displaying the text of the node.

Workaround: display the text of the node offscreen.

I'm using GDevelop5 beta 92.

**Comment by desplesda** [comment] 2020-05-22 01:58
The environment that Yarn scripts in GDevelop runs in is not actually this repo - please file an issue at https://github.com/hylyh/bondage.js/issues! I'll go ahead and close this issue now - thanks for filing it!

(Just to be sure, I tested it in this repo - I'm not able to reproduce the issue in the following script:)

```
title: Start
---
<<test_command>>
===
```

Running this node causes Yarn Spinner to produce the command `test_command`.

**Closed by desplesda** 2020-05-22 01:58 UTC
Labels: bug
